# Generated by Django 4.2.6 on 2023-10-24 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'tb_clientes',
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'tb_fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=100)),
                ('nivel_acesso', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'tb_funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField()),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.clientes')),
            ],
            options={
                'db_table': 'tb_vendas',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_estoque', models.IntegerField()),
                ('fornecedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.fornecedores')),
            ],
            options={
                'db_table': 'tb_produtos',
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.produtos')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.vendas')),
            ],
        ),
    ]
