# Generated by Django 4.2.6 on 2023-10-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itens',
            table='tb_itens',
        ),
    ]
