# Generated by Django 4.2.6 on 2023-10-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_itens_qtd_alter_fornecedores_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='qtd',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qtd_estoque',
            field=models.IntegerField(),
        ),
    ]
