# Generated by Django 4.2.6 on 2023-10-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_itens_qtd_alter_clientes_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='qtd',
            field=models.IntegerField(default=1),
        ),
    ]
