# Generated by Django 4.2.6 on 2023-10-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_itens_qtd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='bairro',
            new_name='cliente_bairro',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='cep',
            new_name='cliente_cep',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='cidade',
            new_name='cliente_cidade',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='complemento',
            new_name='cliente_complemento',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='celular',
            new_name='cliente_contato',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='endereco',
            new_name='cliente_endereco',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='estado',
            new_name='cliente_estado',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='numero',
            new_name='cliente_numero',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='telefone',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_cpf',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_email',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_rg',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='rg',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
